# Generated by Django 5.2.3 on 2025-12-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanevent',
            name='address',
            field=models.CharField(blank=True, help_text='Human-readable address', max_length=500, null=True),
        ),
    ]
