# Generated by Django 5.2.3 on 2025-12-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_scanevent_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanevent',
            name='scan_type',
            field=models.CharField(choices=[('arrival', 'Príchod'), ('departure', 'Odchod')], default='arrival', max_length=10),
        ),
    ]
