# Generated by Django 5.2.3 on 2025-12-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
