# Generated by Django 5.2.3 on 2025-12-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_vacation_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacation',
            options={'ordering': ['-date_from']},
        ),
    ]
