# Generated by Django 5.2.3 on 2025-12-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_vacation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
