# Generated by Django 5.2.3 on 2025-12-12 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_vacation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Magazine', max_length=255)),
                ('issue_number', models.CharField(default='1', max_length=50)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_date', models.DateField()),
                ('template_id', models.CharField(default='classic', max_length=50)),
                ('primary_font', models.CharField(default='Playfair Display', max_length=100)),
                ('secondary_font', models.CharField(default='Lato', max_length=100)),
                ('primary_color', models.CharField(default='#1a1a1a', max_length=20)),
                ('secondary_color', models.CharField(default='#666666', max_length=20)),
                ('background_color', models.CharField(default='#ffffff', max_length=20)),
                ('text_color', models.CharField(default='#2d2d2d', max_length=20)),
                ('language', models.CharField(default='en', max_length=5)),
                ('print_bleed', models.BooleanField(default=False)),
                ('categories', models.TextField(default='News,Features,Opinion,Culture,Sports')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazines', to='viewer.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_magazines', to='viewer.user')),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='MagazineArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('teaser', models.TextField(blank=True, help_text='Short teaser for cover/TOC', null=True)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_main_story', models.BooleanField(default=False)),
                ('is_secondary_story', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='magazine_images/')),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in magazine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='viewer.user')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='viewer.magazine')),
            ],
            options={
                'ordering': ['magazine', 'order', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='magazine_content/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_caption', models.CharField(blank=True, max_length=500, null=True)),
                ('font_family', models.CharField(blank=True, max_length=100, null=True)),
                ('font_size', models.CharField(blank=True, choices=[('sm', 'Small'), ('base', 'Base'), ('lg', 'Large'), ('xl', 'Extra Large')], max_length=10, null=True)),
                ('text_color', models.CharField(blank=True, max_length=20, null=True)),
                ('background_color', models.CharField(blank=True, max_length=20, null=True)),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('justify', 'Justify')], default='left', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='viewer.magazinearticle')),
            ],
            options={
                'ordering': ['article', 'order'],
            },
        ),
    ]
