# Generated by Django 5.2.3 on 2025-12-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_magazine_magazinearticle_contentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='cover_background_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
