# Generated by Django 5.2.3 on 2025-12-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_magazine_cover_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='cover_header_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=20),
        ),
    ]
