# Generated by Django 5.2.3 on 2025-12-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_magazine_cover_header_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazinearticle',
            name='status',
        ),
        migrations.AlterField(
            model_name='magazine',
            name='cover_background_image',
            field=models.URLField(blank=True, default='/static/images/pozadie_1.jpg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='cover_header_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='top', max_length=20),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='tagline',
            field=models.CharField(blank=True, default='An awesome magazine', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='magazinearticle',
            name='teaser',
            field=models.TextField(blank=True, default='Teaser text', help_text='Short teaser for cover/TOC', null=True),
        ),
    ]
