# Generated by Django 5.2.3 on 2025-12-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_remove_magazinearticle_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='background_color',
            field=models.CharField(default='#1a1a1a', max_length=20),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='text_color',
            field=models.CharField(default='#1a1a1a', max_length=20),
        ),
    ]
