# Generated by Django 5.2.3 on 2025-12-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_alter_magazine_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazinearticle',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Image displayed in article header', null=True, upload_to='magazine_headers/'),
        ),
        migrations.AddField(
            model_name='magazinearticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Koncept'), ('published', 'Publikovaný')], default='draft', max_length=10),
        ),
    ]
