# Generated by Django 5.2.9 on 2026-01-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_magazinearticle_header_image_magazinearticle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_edit_absences',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_employees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_qr_codes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='working_hours',
            field=models.IntegerField(default=160),
        ),
    ]
