# Generated by Django 5.2.9 on 2026-01-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_user_can_edit_absences_user_can_edit_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
