# Generated by Django 5.2.9 on 2026-01-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_vacation_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('company', 'Company'), ('user', 'User')], max_length=10)),
                ('actor_email', models.EmailField(max_length=254)),
                ('actor_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('login', 'Login'), ('logout', 'Logout')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='viewer_audi_timesta_d0c4fa_idx'), models.Index(fields=['actor_email'], name='viewer_audi_actor_e_b1aa3d_idx'), models.Index(fields=['model_name'], name='viewer_audi_model_n_0ac018_idx')],
            },
        ),
    ]
