# Generated by Django 5.2.9 on 2026-01-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0016_auditlog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='viewer_audi_model_n_0ac018_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_id',
        ),
    ]
