# Generated by Django 5.2.9 on 2026-01-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0017_remove_auditlog_viewer_audi_model_n_0ac018_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='holidays_per_year',
            field=models.IntegerField(default=20),
        ),
    ]
