# Generated by Django 5.2.9 on 2026-01-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0018_user_holidays_per_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_lunch_breaks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scanevent',
            name='scan_type',
            field=models.CharField(choices=[('arrival', 'Príchod'), ('departure', 'Odchod'), ('lunch_break_start', 'Prestávka začiatok'), ('lunch_break_end', 'Prestávka koniec')], default='arrival', max_length=20),
        ),
    ]
