# Generated by Django 5.2.9 on 2026-01-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0019_company_auto_lunch_breaks_alter_scanevent_scan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='notification_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='notify_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='notify_departure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='notify_lunch_break_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='notify_lunch_break_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_departure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_lunch_break_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_lunch_break_start',
            field=models.BooleanField(default=False),
        ),
    ]
