# Generated by Django 5.2.9 on 2026-01-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0021_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lunch_break_duration',
            field=models.IntegerField(default=30),
        ),
    ]
