# Generated by Django 5.2.9 on 2026-01-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0022_user_lunch_break_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_lunch_break',
            field=models.BooleanField(default=True),
        ),
    ]
