# Generated by Django 5.2.9 on 2026-01-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0023_user_has_lunch_break'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='notify_lunch_break_end',
            new_name='notify_vacation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='notify_lunch_break_end',
            new_name='notify_vacation',
        ),
        migrations.RemoveField(
            model_name='company',
            name='notify_lunch_break_start',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_lunch_break_start',
        ),
    ]
