# Generated by Django 5.2.9 on 2026-01-11 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0025_user_birth_date_user_phone_user_rc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanevent',
            name='is_home_office',
            field=models.BooleanField(default=False, help_text='Indicates if this is a home office scan'),
        ),
        migrations.AlterField(
            model_name='scanevent',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='viewer.qrcodeprofile'),
        ),
    ]
