# Generated by Django 5.2.9 on 2026-01-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0026_scanevent_is_home_office_alter_scanevent_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, default=None, help_text='Mesto', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='dic',
            field=models.CharField(blank=True, default=None, help_text='DIČ - Daňové identifikačné číslo', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ico',
            field=models.CharField(blank=True, default=None, help_text='IČO - Identifikačné číslo organizácie', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, default=None, help_text='Telefón', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, default=None, help_text='Štát', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='street',
            field=models.CharField(blank=True, default=None, help_text='Ulica', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='street_number',
            field=models.CharField(blank=True, default=None, help_text='Číslo domu', max_length=50, null=True),
        ),
    ]
