# Generated by Django 5.2.9 on 2026-01-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0027_company_city_company_dic_company_ico_company_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='zip_code',
            field=models.CharField(blank=True, default=None, help_text='PSČ', max_length=20, null=True),
        ),
    ]
