# Generated by Django 5.2.9 on 2026-01-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0028_company_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanevent',
            name='is_business_trip',
            field=models.BooleanField(default=False, help_text='Indicates if this is a business trip scan'),
        ),
    ]
