# Generated by Django 5.2.9 on 2026-03-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0030_userpasswordsetuptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanevent',
            name='is_no_qr',
            field=models.BooleanField(default=False, help_text='Indicates if this scan was recorded without a QR code'),
        ),
    ]
