# Generated by Django 5.2.9 on 2026-01-16 08:16

from datetime import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='N8nWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Názov workflow')),
                ('workflow_id', models.CharField(max_length=100, unique=True, verbose_name='n8n Workflow ID')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktívny')),
                ('webhook_url', models.URLField(blank=True, max_length=500, verbose_name='Webhook URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'n8n Workflow',
                'verbose_name_plural': 'n8n Workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='N8nWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Názov webhooku')),
                ('endpoint', models.CharField(max_length=255, unique=True, verbose_name='Endpoint URL')),
                ('webhook_type', models.CharField(choices=[('incoming', 'Prichádzajúci (od n8n)'), ('outgoing', 'Odchádzajúci (do n8n)')], default='incoming', max_length=20, verbose_name='Typ webhooku')),
                ('secret_key', models.CharField(blank=True, max_length=255, verbose_name='Tajný kľúč')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktívny')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='HTTP Headers')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Konfigurácia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='n8n_integration.n8nworkflow')),
            ],
            options={
                'verbose_name': 'n8n Webhook',
                'verbose_name_plural': 'n8n Webhooky',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='N8nTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Názov triggeru')),
                ('trigger_type', models.CharField(choices=[('scan', 'QR Scan'), ('user_register', 'Registrácia používateľa'), ('vacation_request', 'Žiadosť o dovolenku'), ('magazine_publish', 'Publikácia magazínu'), ('custom', 'Vlastný')], max_length=50, verbose_name='Typ triggeru')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktívny')),
                ('conditions', models.JSONField(blank=True, default=dict, verbose_name='Podmienky spustenia')),
                ('trigger_count', models.IntegerField(default=0, verbose_name='Počet spustení')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Posledné spustenie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='n8n_integration.n8nworkflow')),
            ],
            options={
                'verbose_name': 'n8n Trigger',
                'verbose_name_plural': 'n8n Triggery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='N8nExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(blank=True, max_length=100, verbose_name='Execution ID')),
                ('status', models.CharField(choices=[('pending', 'Čakajúce'), ('running', 'Bežiace'), ('success', 'Úspešné'), ('error', 'Chyba'), ('cancelled', 'Zrušené')], default='pending', max_length=20, verbose_name='Stav')),
                ('request_data', models.JSONField(default=dict, verbose_name='Request Data')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Response Data')),
                ('error_message', models.TextField(blank=True, verbose_name='Chybová správa')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresa')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('started_at', models.DateTimeField(default=datetime.now, verbose_name='Začaté')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Skončené')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='Trvanie (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Používateľ')),
                ('webhook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='n8n_integration.n8nwebhook')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='n8n_integration.n8nworkflow')),
            ],
            options={
                'verbose_name': 'n8n Execution Log',
                'verbose_name_plural': 'n8n Execution Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='n8n_integra_created_e59ecb_idx'), models.Index(fields=['status'], name='n8n_integra_status_c95d8d_idx'), models.Index(fields=['workflow'], name='n8n_integra_workflo_57eae2_idx')],
            },
        ),
    ]
