services:
  web:
    container_name: qr_reader
    build: .
    ports:
      - "9005:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - DEBUG=True
    restart: unless-stopped